### ISSUE TITLE
Implement bitwise boolean opeartors

### ISSUE THREAD

**Issue by ghost** [mit-cml/appinventor-sources#1017]
As in subject, please, add those two simple features to AI2:
Xor operator block
Bitwise boolean operators

Thanks in advance if you do.

**Comment by ewpatton** [comment]
This would be useful for IOT work due to the bit fiddling that is sometimes required to talk to devices (micro:but I/O pin comes to mind) but we also need to think about how these apply generally to RatNums and whether we floor rationals to ints or whether a bit wise operator on a non-int results in an error.

**Comment by mrrm92** [comment]
Note the XOR operator is just:
((a AND NOT b) OR (NOT a AND b)), it could be done just using existing boolean operators, instead of doing it from scratch.

**Comment by ewpatton** [comment]
Resolved by #1354
