### ISSUE TITLE
Improve BlocklyEditor translation

### ISSUE THREAD

**Issue by barreeeiroo** [mit-cml/appinventor-sources#1021]
Today I was checking how BlocklyEditor translations works, because in Makeroid **translations aren't applied**
And I just went to the conclusion that if, for example, the `es_es` file doesn't have ALL required strings, it's ignored and used English one. So, this comes to a problem when missing translations
So, I'm just wondering if there's a way to fix this and improve it. Maybe by using `OdeMessages` instead of the `msg `folder; I don't know
And, also, the `_messages.js` file structure isn't supported by online translation centers, which would be a great option to allow users to translate the files

But in my opinion, this is a big problem

**Comment by ewpatton** [comment]
The translations for the blocklyeditor can come from three different places. Most strings from Blockly core are provided by translatewiki via Google. We pull those in from upstream without any modification to the strings. We then extend the Blockly.Msg namespace with App Inventor specific translations in blocklyeditor/src/msg. Lastly, component translations are provided by passing in a dictionary constructed in ComponentTranslations.java to the ComponentDatabase object in blocklyeditor/src/component_database.js. Your suggestion of using OdeMessages doesn't solve the problem either, because OdeMessages works in the same way--in the event a string isn't translated, it falls back to the English version (specifically, the default language, which is specified in YaClient.gwt.xml, and App Inventor's default is en). The topic of better handling translations is a recurring discussion on the App Inventor team and we are still seeking better models to follow.

**Comment by barreeeiroo** [comment]
But isn't that process a bit hard? And the translatewiki is only compatible with OpenSource projects
Wouldn't be better to store them with the OdeMessages strings?

**Comment by ewpatton** [comment]
It's unclear what you mean by "that process." The issue is that GWT handles translations as part of its compilation by creating a version per language when the Java is transpiled to JavaScript. Blockly is already in JavaScript, and so it needs the translations represented in a way that is friendly to the JavaScript (which the OdeMessages mechanism is not--it does not exist at runtime because the calls to the functions in OdeMessages are replaced at compile time by GWT).

**Comment by barreeeiroo** [comment]
Okey, thank you anyway 👍

**Comment by ewpatton** [comment]
The translation problem is a hard problem and as I said we continue to think about it. In general I do think it would be good to only have a single file that needs to be updated, but the current structure of the system doesn't allow that right now. As we continue to think about translations we will keep your concerns in mind.
