### ISSUE TITLE
Error on hide keybooard if keyboard never opened

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#1059]
If  create a screen that contains only  canvas, and execute Hide Keyboard, then 
I get 

error 906:  No focusable view found

**Comment by ewpatton** [comment]
Was the keyboard open when you attempted to do this? Looking at the code for [HideKeyboard](https://github.com/mit-cml/appinventor-sources/blob/ba120fc773b654ea8c4fe7d9f4877d9e03c816df/appinventor/components/src/com/google/appinventor/components/runtime/Form.java#L2069), it looks like this method only works if a view that is focusable is focused to receive text. Otherwise, if no view is focused the reported error is dispatched.

**Comment by ewpatton** [comment]
@farxinu Do you want to chime in here?

**Comment by farxinu** [comment]
Oh hey. Yes. I didn't see this before. I will take a look. I'm on the T right now so can you assign it to me?

Sent from mobile. Please excuse any brevity.




On Tue, Dec 19, 2017 at 8:40 AM -0500, "Evan W. Patton" <notifications@github.com<mailto:notifications@github.com>> wrote:


@farxinu<https://github.com/farxinu> Do you want to chime in here?
