### ISSUE TITLE
Implement break in while and for-each loops

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#1095]
This looks like it might be easy because kawa' limited form of call-with-current-continuation should be sufficient to handle this.

Should we call it "break" or "exit"?

**Comment by pavi2410** [comment]
Also a continue block.

**Comment by moliata** [comment]
I would stay with break and also as @pavi2410 said we should add continue block too.

**Comment by ewpatton** [comment]
@halatmit Agreed on the call/cc support. I think that we can really get 8 different blocks from Kawa's functionality:

- exit loop
- exit loop if <conditional>
- continue
- continue loop if <conditional>
- return from procedure
- return from procedure if <conditional>
- return from procedure <value>
- return from procedure <value> if <conditional>

The conditional versions are syntactic sugar for building `if <conditional> <action>`. The two different return versions are to handle procedures with/without return values.

The real trick will be updating the blocks editor so that one can't connect a exit/continue block to a stack outside of a for/while block.

**Comment by halatmit** [comment]
Once we get the basic exit working, we can flesh out the others.

**Comment by halatmit** [comment]
Pull request #1142 implements break from forEach forRange and while.   It does not implement continue or procedure escape.

**Comment by ewpatton** [comment]
Closed with companion release 2.47
