### ISSUE TITLE
Possible Security Bug

### ISSUE THREAD

**Issue by barreeeiroo** [mit-cml/appinventor-sources#1098]
When you login for first time into a AppInventor based service, your username is asigned with everything that is before the @ mail part (for example, `pepito.grillo@gmail.com` becomes `pepito_grillo`)

So, what happens if users signup with these emails? `pepito.grillo@gmail.com` and `pepito.grillo@makeroid.io`.
Will they have the same workspace, as technically they would have the same username `pepito_grillo`? Will they have access to apps from the other user?
And what happens with PackageNames? If they create a `test` project, would both apps have the same PackageName and keystore?

**Comment by moliata** [comment]
@ewpatton please take a look here.

**Comment by ColinTree** [comment]
Wow this could be quite dangerous. Though it is so rare that people got same keystore, it could still causes some other problems. (•́ω•̀ ٥)
Good job to find this.

**Comment by moliata** [comment]
@ColinTree we are not sure yet whether this is a confirmed security vulnerability.

**Comment by conorshipp** [comment]
I actually did this on Thunkable last year. If, for example, I had the account `example@gmail.com` then created another account called `example@domain.com` and set it up to login to Google, when logging into App Inventor (and/or its clones), the projects wouldn't be shared. But if both accounts had an app called `hellopurr`, when they build the APK, the package names for both apps would be the same: `appinventor.ai_example.hellopurr`.

**Comment by ColinTree** [comment]
@moliata I think it should be one. And i m testing it now.

**Comment by ColinTree** [comment]
@conorshipp Did you compare the keystore files? App would not be re-install if the keystore(signature) is different

**Comment by conorshipp** [comment]
> @conorshipp Did you compare the keystore files? App would not be re-install if the keystore(signature) is different

Nope, I didn't think about that.

**Comment by moliata** [comment]
@ColinTree depending on what @conorshipp said, keystores are not being shared, besides the same package name. This is caused by appinventor/common/src/com/google/appinventor/common/utils/StringUtils.java taking the first part of the email address (until @ sign). In the future, we need a to find better mechanism of handling that.

**Comment by ColinTree** [comment]
Yep. I tested locally: people could not re-install the others' application though they have a same package name because of the difference between keystore files. But changes should be taken to get rid of this.

**Comment by ewpatton** [comment]
This is not a problem.

First, we don't allow local login on the production system--one can only use Google (who gives a unique ID). When we look up a user locally, we look them up by their full email address, first by case and then case insensitively (see [ObjectifyStorageIo.getUserFromEmail](https://github.com/mit-cml/appinventor-sources/blob/75cd041257f8686779a3394fdc203d25b5911579/appinventor/appengine/src/com/google/appinventor/server/storage/ObjectifyStorageIo.java#L338)), so there won't be a collision because we aren't discarding the email domain.

Second, when we create a user, we generate a random UUID for them, and all files are keyed off of this either directly or indirectly. This is also an ID field in Objectify, so if there were ever a collision (very unlikely as we are talking 2^124 possible random UUIDs), we would be informed and the creation would not take place. Further Google uses a ID format that is not a UUID, so our created identifiers can't clash with the Google identifiers.

The only place this does become a problem is (as was pointed out in the thread) is that the package names can collide. However, this requires both users to have the same username before the @ in the email address AND they have to have the same project name AND they both have to be willing/interested in publishing that project to the Google Play Store. We think the odds of all of these conditions happening are relatively low. Plus there are tools like AppToMarket that enable changing the package name in the event there ever was a collision.

**Comment by moliata** [comment]
@ewpatton that's what I said, the only problem is the package name.
But I am concerned with one thing, what if a person uses G Suite? This would still cause the issue. Maybe those conditions happen relatively low, we need to take a look into using a better mechanism of handling that. We could pass a user's UUID to be part of package name.

**Comment by kkashi01** [comment]
@moliata package naming convention can't be changed because it'll impact existing published apps and users won't be able to publish new versions of their apps

**Comment by moliata** [comment]
That's true, didn't think about that. Well either we ignore people with same email address until @ part or we ignore people who already published their apps. I think it's better to keep our current mechanism.

**Comment by ewpatton** [comment]
@moliata I think AppToMarket allows one to change the package name, in which case if people really run into a conflict they can change the name outside of App Inventor before submitting to the Play Store. They could also rename the project--if someone has published an app with the same name it's probably better to try to be more original.

**Comment by moliata** [comment]
@ewpatton, that's true.

**Comment by ewpatton** [comment]
Closing this issue as I do not see any evidence that it is a real problem. User data is keyed off of a unique ID and login is performed based on the whole email address. The only possible problem (which we have never seen with App Inventor users) is collisions on package name when publishing an app, but if this really occurs with two separate individuals I would just encourage them to change the name of the project, which is easy enough to do.
