### ISSUE TITLE
About Menu Crashes in New APK files

### ISSUE THREAD

**Issue by farxinu** [mit-cml/appinventor-sources#1125]
In a newly built apk, hitting the three dots at the bottom to pull up the About App options causes the app to crash.

**Comment by josmas** [comment]
@farxinu any chance you can attach the LogCat output for this?

**Comment by farxinu** [comment]
It's here. @ewpatton is now looking into it. 

[dump.txt](https://github.com/mit-cml/appinventor-sources/files/1623358/dump.txt)

**Comment by ewpatton** [comment]
This seems to only happen in compiled apps with the Classic theme. It looks like the AppCompatDelegate still installs a layout inflater for the menu even if it throws due to the action bar not being available. However, the Classic theme doesn't reference the AppCompat layout files needed for the menu items.
