### ISSUE TITLE
Navigationbar in landscape mode is on wrong side

### ISSUE THREAD

**Issue by Mika-89** [mit-cml/appinventor-sources#1201]
On every android device is the navigationbar in landscpae mode on the right side.
![01](https://user-images.githubusercontent.com/29900947/38241482-a6216eee-3732-11e8-8dac-c7ffea9f1318.png)

On the app inventor phone preview is it on the bottom side.
![01 - kopie](https://user-images.githubusercontent.com/29900947/38241530-c254bae4-3732-11e8-8533-d3ab10ee6d5e.png)

**Comment by kwankiu** [comment]
I think some tablet and android 2.x's navigation bar is at the bottom, isn't it ?

**Comment by utkarshg6** [comment]
I am a student of GSoC and I would like to work on this issue. Can anyone tell me which files to look into for making changes?

**Comment by NmdOfficial** [comment]
The file where all is done is the MockForm file

**Comment by utkarshg6** [comment]
> I think some tablet and android 2.x's navigation bar is at the bottom, isn't it ?

I think for the screen with this aspect ratio usually have the Navigation bar at the right side.

**Comment by utkarshg6** [comment]
Hey, @NmdOfficial , to make changes I think we need to create an if condition in `class NavigationBar ` that checks `if ( PROPERTY_NAME_SCREEN_ORIENTATION == "landscape")` and then make changes in that if condition. Am I thinking correct?

**Comment by ewpatton** [comment]
@utkarshg6 That sounds like a good start. One problem is that currently the navbar is implemented as a single horizontal image. What we should consider doing instead is having 3 images representing each of the different buttons, and then we can use CSS rules to position them horizontally or vertically.

**Comment by ewpatton** [comment]
If we use CSS, we can apply the appropriate class to the navigation bar in [`setScreenOrientationProperty(String)`](https://github.com/mit-cml/appinventor-sources/blob/5389d42648b9b11ac94be3f5c6cd8e8c228c032e/appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockForm.java#L517).

**Comment by utkarshg6** [comment]
@ewpatton I think instead of using three images of diffrent buttons we can use these horizontal and vertical images of  newer navigation bar by Google. Does this looks like a good idea?

### Vertical
![Group 295](https://user-images.githubusercontent.com/32920299/54477249-1fc0ca00-482c-11e9-87e6-264e3435831c.png)

### Horizontal
![navbar](https://user-images.githubusercontent.com/32920299/54477155-15ea9700-482b-11e9-9033-d973fb153ae6.png)

**Comment by ewpatton** [comment]
@utkarshg6 That sounds like a reasonable approach. The benefit of breaking into three smaller images would be the possibility of reducing the file size by reusing the three smaller pieces to compose the toolbar rather than storing two larger images. Given that they are PNG files, it might not make that much of a difference though.
