### ISSUE TITLE
Number block accepts non-number value

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1238]
Typically, the number block rejects values that do not parse as numbers. For example, typing `cat` and pressing enter will reject the string and revert the block to its original value. However, if one clicks on the workspace background the block will accept the change.

**Comment by ColinTree** [comment]
Refer to this line

https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/blocklyeditor/src/blocks/math.js#L24

I wondered why we use
`new Blockly.FieldTextInput('0', Blockly.Blocks.math_number.validator)` (Text field with a custom validator)
instead of
`new Blockly.FieldNumber(0)` (blockly built-in number field)
directly?

**Comment by ewpatton** [comment]
@ColinTree The implementation of the number block in App Inventor predates the implementation of `Blockly.FieldNumber`. I'm not opposed to switching from our existing implementation to `FieldNumber`, but it will need significant testing to ensure we don't break existing apps when we switch.

**Comment by SusanRatiLane** [comment]
Additional testing indicates that this is a display problem. The change event for the number block is never called, and the stored value is not saved. The block displays as if it has changed until the project is reloaded.

**Comment by BeksOmega** [comment]
Dug into this a bit b/c fields are my jam. Turns out this is a bug inside Blockly, but it's fixed in the latest version.

Explanation of why this occurs:
1. When you enter "cat" the validator returns null [here](https://github.com/mit-cml/appinventor-sources/blob/7f0e248486e100ab10c83daa85def731c63b744f/appinventor/blocklyeditor/src/blocks/math.js#L35).
2. This causes the field to reset the text to the previous value [here](https://github.com/mit-cml/blockly/blob/ddb37e2ebf89deec0a4a43d0327c79c453ebf687/core/field_textinput.js#L297).
3. Then when the base setValue gets called [here](https://github.com/mit-cml/blockly/blob/ddb37e2ebf89deec0a4a43d0327c79c453ebf687/core/field_textinput.js#L306) it sees that the old value and new value match [here](https://github.com/mit-cml/blockly/blob/ddb37e2ebf89deec0a4a43d0327c79c453ebf687/core/field.js#L454).
4. So setText never gets called, so it still displays "cat".

It could be fixed by monkey-patching the individual field's setValue function. Or by monkey-patching Blockly.Field's setValue function. But those aren't great options :/

**Comment by ewpatton** [comment]
@BeksOmega I would just go ahead and monkey patch it.
