### ISSUE TITLE
Typeblock code gets very confused by too many escapes

### ISSUE THREAD

**Issue by farxinu** [mit-cml/appinventor-sources#1280]
If you open a block drawer, and then hit escape at least five times (or just hold down the key), it causes the entire browser tab to become unresponsive. Depending on how many escapes were recorded and how powerful your machine is, you may or may not recover. 
We're approximating an n^2 growth of listener events. 
Issue is in typeblock.prototype.hide, where the escape press is handled.

**Comment by ewpatton** [comment]
The problem is that if `hide` is called multiple times in a row, it attempts to [clean up `handleKeyWrapper_` on `inputKh_` but it registers on `docKh_`](https://github.com/mit-cml/appinventor-sources/blob/cbbb28ca2195472c74b9fcd9bc65677ddeb27a05/appinventor/blocklyeditor/src/typeblock.js#L215). This works in the general flow of typeblock (since showing does the opposite). Subsequent calls to either `show` or `hide` will attempt to unlisten from the wrong DOM element. I propose that instead of reusing `handleKeyWrapper_` for multiple purposes, we have one wrapper per element to make the relationship explicit, then update the code in `show` and `hide` to unlisten for the correct pairs.
