### ISSUE TITLE
Wake lock for screens

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1284]
A wake lock may need to be added, since it is quite useful. And it just needs a new property that can handle the flag.

**Comment by ewpatton** [comment]
The wake lock issue has come up a number of times in the past. My general recollection of the issue is that for our educational goal it is too low level a detail to expose in App Inventor. Components/extensions should manage the wake lock as needed to perform their functions but control over the wakelock shouldn't be something directly exposed to the user. I think this is something better left to an extension rather than added to core App Inventor.
