### ISSUE TITLE
Recreate screen - Why ?

### ISSUE THREAD

**Issue by michael-winkler** [mit-cml/appinventor-sources#1349]
Why do we call "recomputeLayout();" on onConfigurationChanged ?
It does not make any sense to me to recreate all after such a change.

**Comment by ewpatton** [comment]
The important part of this is really in handling the Sizing property and updating the width/height of all components that are a percent of the screen size due to going from one orientation to another. We might be able to optimize by refactoring [Form.java lines 966-962](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/components/src/com/google/appinventor/components/runtime/Form.java#L966) into its own method and calling it from both onConfigurationChanged and recomputeLayout.

**Comment by NmdOfficial** [comment]
Is a call on the main layout with invalidate or requestlayout not enough for that kind of redraw?
