### ISSUE TITLE
Button bug - width is not returned correct

### ISSUE THREAD

**Issue by michael-winkler** [mit-cml/appinventor-sources#1370]
![blocks](https://user-images.githubusercontent.com/29900947/45873645-3b727880-bd93-11e8-80cd-4089636507e1.png)

When I click now the button for one time I get not 300 back as result in the label text.
The wrong value I get is something like "122" but not 300.
(NOTICE)
Just the return value is wrong, the button width is set correct on screen.

**Working solution to get the correct result:**
I have to click now two times on the button to get the correct value of 300 in the label text.

Here is one bug report on appy builder:
https://community.appybuilder.com/t/resizing-property-bug/16137

I got the same bug, in app inventor, appy builder, makeroid, thunkable.

**Comment by ewpatton** [comment]
This is due to the fact that once we update the layout parameters a pass needs to be made to update the view. The updated layout isn't applied until the next render pass, and that doesn't occur until after the blocks finish executing. This isn't so much a bug as a mismatch between people's perceptions and the actual event processing model in App Inventor / Android.
