### ISSUE TITLE
APK build failed in projects with specific name

### ISSUE THREAD

**Issue by Donlon** [mit-cml/appinventor-sources#1386]
Hi, I'm building my app using App Inventor in http://ai2.appinventor.mit.edu. I failed to generate APK file and got some strange error outputs as following:

> ________Preparing application icon
> ________Creating animation xml
> ________Creating style xml
> ________Generating manifest file
> ________Attaching native libraries
> ________Attaching Android Archive (AAR) libraries
> ________Attaching component assets
> ________Invoking AAPT
> AAPT time: 0.692 seconds
> ________Compiling source files

which actually doesn't contain useful information to pinpoint where errors located. So I built my local AI server and noticed that terminal output said 

> ERROR in C:\Users\Administrator\AppData\Local\Temp\1538879186861_0.4665875202881149-0\build\generated\src\appinventor\ai_test\try\R.java (at line 8)
>         package appinventor.ai_test.**try**;
> Syntax error on token "try", Identifier expected

It indicates that the project name ("try") conflicts with Java keywords. So if some users type names like "package", "long", "private" and so on accidentally to their project, they will encounter identical error messages when building. To avoid this annoying circumstance, I suggest adding a prefix for project name in source file to compile.

**Comment by moliata** [comment]
Have you updated your instance of the App Inventor? PR 1348 should have fixed that

**Comment by Donlon** [comment]
@moliata Thanks, I've checked my files and it turns out that my BuildServer is built from the latest sources code but front-end "YaClient" is not. The latest version does work.
To @SusanRatiLane and @ewpatton who is related to #1348, I've read #1348 which solved this by preventing users to create "illegal" things, and it just verifies the name in user's browser, anyway, I don't consider it as an elegant way to solve this problem. Users might be annoyed by the tips (and might say App Inventor is so bad because it even can't accept such simple common words [sad...]). Why not just adding a prefix to every vulnerable field, thus give back more freedom of choice to users?
And I noticed that using screens or components named after reserved words seems doesn't lead to such errors, maybe that's because Screens' classes are compiled with YAIL (or kawa) compiler.

**Comment by ewpatton** [comment]
The primary reason we can’t do what you propose is due to backwards compatibility. It was a design decision that the project name be used to construct the package name for the app. If we introduce a prefix to protect package names, then it will prevent people from publishing new versions of their apps in the Play store (without repackaging using their old package name) and breaks any uses of ActivityStarter that might rely on the package name.

For users who are upset that App Inventor doesn’t allow trivial names for projects, I would recommend that they reconsider and choose a project name that more accurately describes what the app is attempting to solve. Otherwise one may just end up with a list of project names that are without meaning. At the very least, I think it would make sense to start with a capital letter. But rather than forcing naming conventions on people, it is less friction to just disallow reserved words like any other compiler would.

**Comment by Donlon** [comment]
Thanks for your reply.
