### ISSUE TITLE
Remove from backpack fails for duplicate blocks

### ISSUE THREAD

**Issue by SusanRatiLane** [mit-cml/appinventor-sources#1467]
If a block is added to the backpack, then then the same block added again, "Remove from Backpack," on the second block in the backpack does nothing. 

Should it even be possible to add the same block to the backpack multiple times? The same one can already be dragged from the backpack multiple times.

**Comment by ewpatton** [comment]
So here's the issue. The problem occurs when you add EXACTLY the same block to the backpack twice. The reason this is a problem is because we serialize the block to an XML string, and the backpack is just an array of these. When you open the backpack, the strings are parsed into an XML DOM, and then then each set in turn is converted into blocks to be appended to the workspace. Now, when you parse the second copy of the block, there is an block ID collision, so the second block gets a new ID. When you right-click and say Remove from Backpack, that ID is handed back and we remove the string with the block ID matching the root block. This fails because the block ID is fresh and therefore doesn't match the block ID in the string. Also, the way the code is written, the reverse behavior is also true. If you remove the first of the copies, both will be removed (since the ID matches twice).

We don't currently check for the existence of a block stack in the backpack, and I don't know that that would be the right approach to fixing this, mainly because I could imagine that someone might create a stack of blocks, add them to the backpack, and then make a modification, add that to the backpack, and so forth, as a rudimentary checkpointing system where they can recall previous versions of the code. All of these stacks will have the same root block ID. Instead, we could try to store the index of the block in the list, and then use that to remove it from the array, as that index will be a 1-1 mapping.

**Comment by BeksOmega** [comment]
Hello,

I'm not completely versed in how app inventor works but I recently added a flyout to the trashcan (so you can get back deleted blocks) based on the way the backpack works, and I figured out a way to disallow duplicate blocks.

I believe all I would have to do is change [this](https://github.com/mit-cml/appinventor-sources/blob/63738ecb43e80f7eee199181858a186ce19a0501/appinventor/blocklyeditor/src/backpack.js#L340) to do something like [this](https://github.com/BeksOmega/blockly/blob/77ee4c8e22b41f7f127bda05833ec929829263d8/core/trashcan.js#L481).

Do you think that would work/is this something you'd be interested in a PR for?

**Comment by ewpatton** [comment]
@BeksOmega I'm not sure I follow how your suggested change prevents duplicate blocks, unless at some other point in your code you are comparing all of the strings you are putting into your content array. My reading of the code you linked is that it normalizes the blocks by removing all ids and coordinates. The proposed change would also break how our code for removing an individual block stack from the backpack currently works, since it relies on knowing the top level block ID so that we can identify it in the backpack content array.

**Comment by ewpatton** [comment]
@BeksOmega The trick with your approach will need to be ensuring that the behavior is `O(n)` for operations like Copy All to Backpack. As proposed, it sounds like it would be `O(n^2)`, which for large App Inventor projects will lock up the browser for an extended period of time.

**Comment by BeksOmega** [comment]
So if I understand correctly you're saying that the code would look something like this:
```
addToBackpack() {
  foreach (wsBlock in workspace) {
    var isInBackpack = false;
    //This is the indexOf function
    foreach (bpBlock in backpack) {
      if (bpBlock == wsBlock) {
        isInBackpack = true;
      }
    }
    if (!isInBackpack) {
      addToBackpack(wsBlock)
    }
  }
}
```
And the foreach loop inside the foreach loop would kill larger projects. Hm...

Well we obviously couldn't get rid of the outer loop, so we would need to do something with the inner one. Maybe we could store it as some sort of map instead of as an array? Then it would look more like this:

```
addAllToBackpack() {
  foreach (wsBlock in workspace) {
    //This could be the cleaned XML or something else that is based on the block's structure
    var key = getKey(wsBlock).; 
    if (!map[key]) {
      map[key] = cleanXML(wsBlock);
    }
  }
}
```

What do you think of doing something like that?

**Comment by ewpatton** [comment]
Yes, the latter is more appropriate. If you look at the history of Blockly's events.js file, and in particular the Blockly.Events.filter method, you'll see that we did a similar rewrite to deal with nested for loops to reduce the computational complexity of the method (for reference, some App Inventor projects have O(1000) top level blocks and O(10000) total blocks).

**Comment by BeksOmega** [comment]
Hello,

I noticed that getContents returns an array rather than a hashmap like we want to change it to, but it's a public function so I don't want to change what it returns. So I'm wonder what the best approach would be for accessing the hashmap. Here are a few ideas:

1) Have .getContents set the .contents property (public) as well as a .contentsHash_ property (private) and then any callback functions (defined in the backpack) would only access the properties of the backpack.

```
.getContents = function(callback) {
  Blockly.backpack.contents = contentsArray;
  Blockly.backpack.contentsHash_ = contentsHash;
}

.removeFromBackpack = function(blocks) {
  var backpack = this;
  this.getContents(function(contentsArray) {
    if (backpack.contents.length) { //property of backpack
      for (var i = 0; i < blocks.length; i++) {
        if (backpack.contentsHash_[blockXML]) { //property of backpack
          delete backpack.contentsHas_[blockXML]; //property of backpack
        }
      }
    }
  }
}
```


2) Change getContents to just be the public accessor, while something like .getContentsPrivate_ would return an array & a hashtable.
```
this.getContents(function(contentsArray) {
  // Do stuff with the contentsArray
}

this.getContentsPrivate_(function(contentsArray, contentsHash) {
  // Loop over the contents array (e.g. openBackpack)
  // or use the hash for contains-checking (e.g. addBlockToBackpack)
}
```
What would be your prefered approach?

P.S: The setContents function also takes in an array, and I believe it is stored a an array server-side if that has any influence on your opinion :D
