### ISSUE TITLE
v4-support.jar seems empty

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1494]
https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/lib/android/support/support-v4-26.1.0.jar

This empty jar got only 1kb, and would eclipse classpath not work with this while some code references the v4 support classes (e.g. ActivityStarter requires FileProvider)

**Comment by ewpatton** [comment]
FileProvider is located in support-core-utils. If you are importing into Eclipse, you should include all of the JAR files in that directory to resolve imports.

Once upon a time, all of the support files were in support-v4, but Google decided to split them out into different parts so that different subsets could be included without including everything. I believe now it's just left to include the BuildConfig, which the other dependencies rely on.
