### ISSUE TITLE
ant build fail: build.xml:21

### ISSUE THREAD

**Issue by alineniggeler** [mit-cml/appinventor-sources#1514]
building the appinventor-sourcers with ant, before the "new" release with webRTC worked fine for me but since then I get the following error message:

BUILD FAILED
/home/aline/appinventor-sources/appinventor/build.xml:21: The following error occurred while executing this line:
/home/aline/appinventor-sources/appinventor/buildserver/build.xml:237: Java returned: 1

java version: 10.0.2 2018-07-17 for ubuntu
javac version: 1.8.0_191
ant: 1.10.3 compiled on July 19 2018
OS: ubuntu and windows 10

What am I missing? Thanks for resolving

**Comment by ewpatton** [comment]
master builds for us, so please ask about issues related to your specific setup in the [App Inventor open source forum](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev). You should also provide information about the build prior to the BUILD FAILED message so that we can better assist you.
