### ISSUE TITLE
Safari doesn't like WebRTC

### ISSUE THREAD

**Issue by barreeeiroo** [mit-cml/appinventor-sources#1530]
As the title sais, it seems like Safari doesn't like the new WebRTC implementation. One of our users reported that they cannot use the Companion in Safari, but it worked in Chrome.
Safari's console output was this:

![image](https://user-images.githubusercontent.com/19251112/51446433-728d7200-1d12-11e9-9b98-f28aca3ca301.png)
![image](https://user-images.githubusercontent.com/19251112/51446435-75886280-1d12-11e9-9798-7b0d77eeca14.png)
![image](https://user-images.githubusercontent.com/19251112/51446439-7d480700-1d12-11e9-9574-574bd1e7f9ff.png)

The user also reported that the issue was on MIT App Inventor 2 when using the WebRTC option in the official Companion, as maybe it could be an issue with our system serving HTTPS.
So, as a conclusion, it seems like the new protocol doesn't work properly on Safari browsers.

**Comment by ewpatton** [comment]
Actually there are two different issues. I just tested WebRTC with Safari 12.0.2 and the WebRTC connection failed due to an exception: `Member RTCIceServer.urls is required and must be an instance of (DOMString or sequence)`. However, the issue that you are facing has to do with the fact that aiStarter doesn't include an SSL certificate and only serves HTTP. You cannot make an HTTP call from a page served over HTTPS. That's the essence of the stack trace you attached. We haven't migrated aiStarter to work with HTTPS yet, which is why we are still using HTTP in production.

**Comment by barreeeiroo** [comment]
@ewpatton But the test wasn't done with aiStarter, it was done using WiFi Network
So, I don't think the issue could be releated with the starter at all, no?

**Comment by jisqyv** [comment]
@ewpatton @barreeeiroo Interestingly, this is due to a TYPO on my part. I meant to type "urls" : ... but instead typed "url" : ... The "url" property is deprecated, but still supported in Firefox and Chrome, but not Safari. Just changing it to "urls" (and making it a list, which isn't necessary) causes it to work in Safari and Chrome (and I need to test Firefox, but I'm about to do that). I'll post a PR in a day or so with the trivial fix (doing a review at the moment)
