### ISSUE TITLE
Companion: project loading issue & merge mistake

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1531]
1. `0d0a` -> `\r\n` brokes appengine loading it:
  ![image](https://user-images.githubusercontent.com/22613139/51459448-a361bb80-1d93-11e9-834d-c87a5525a21d.png)
  ![image](https://user-images.githubusercontent.com/22613139/51459572-f89dcd00-1d93-11e9-8ae9-c5bbe829467c.png)

------

2. This should be a merging mistake? 
  ![image](https://user-images.githubusercontent.com/22613139/51459509-ce4c0f80-1d93-11e9-8791-57e085b2a969.png)

------

Issue by this commit in master: https://github.com/mit-cml/appinventor-sources/commit/3362b27151037ac90b43e5e659b8b9f6cb151774#diff-d5bc043c58ccc2384dbe86edec4acbadR1

**Comment by ColinTree** [comment]
Also, Checkbox1 might need to be renamed with a meaningful name, like `useLegacyCheckbox`.

**Comment by ewpatton** [comment]
If you'd like to submit a patch for handling the possible Windows carriage return, that's fine, but the issue here is that when you use Git for Windows the default behavior is to checkout files using Windows line endings. If you download the raw file from GitHub and look at the line ending for Screen1.scm, you'll see that it's a Unix-style line ending (0x0a), which is what App Inventor is expecting.
