### ISSUE TITLE
Any Component blocks for form show in typeblock but not in palette

### ISSUE THREAD

**Issue by conorshipp** [mit-cml/appinventor-sources#1542]
As you can see from the screenshots below, there is no way to select the "Any Form" blocks from the blocks palette - they can only be accessed by using typeblock.
![image](https://user-images.githubusercontent.com/25845449/51750181-268f5400-20a9-11e9-8433-159583c5b59d.png)
![image](https://user-images.githubusercontent.com/25845449/51750132-08c1ef00-20a9-11e9-8187-59b56810d7c3.png) ![image](https://user-images.githubusercontent.com/25845449/51750104-fa73d300-20a8-11e9-8813-a3d68e9c5977.png)

**Comment by ewpatton** [comment]
Is this a regression? I'm not sure it would make sense to allow for Any Screen blocks because you can only ever access the current screen (in App Inventor at least).

**Comment by conorshipp** [comment]
Yes, you're right, it doesn't make sense to use these blocks, that explains why there's no palette button to access them.

w.r.t. the typeblock, I'm not sure how long this has been happening or when it was introduced. It happens on both ai1 and ai2-test.

**Comment by ProstoSanja** [comment]
The only reason i see to have "Any screen" option, is for when there might be too many screens in project to scroll for specific one, although this one is also pretty stretched argument.
Quick solution to this is in `appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockComponent.java`
where there is currently specific check against it.
Removing it though shows another problem, which is the fact that in appinventor Forms are called Screens.
Quick and dirty solution will be to nest if solution and manually set the name in case of a Screen component.
```
  public void collectTypesAndIcons(Map<String, String> typesAndIcons) {
    String name = getVisibleTypeName();
    if (!typesAndIcons.containsKey(name)) {
      if (isForm()) {
        typesAndIcons.put("Form", iconImage.getElement().getString());
      } else {
        typesAndIcons.put(name, iconImage.getElement().getString());
      }
    }
  }
```
---
Also this is for GSoC application.

**Comment by ewpatton** [comment]
@ProstoSanja I don't think that's the issue here. You'll see that Form/Screen is already filtered out under the "Any Component" category in the structure explorer. The issue raised here is that those blocks still manifest themselves via the typeblocking interface. To prevent that, we need to modify the typeblock function for component_event, component_method, and component_set_get to filter out the Form type.

Note that at this time it isn't possible to make cross-screen calls, so access to these blocks makes no sense as one can only ever reference the current screen.
