### ISSUE TITLE
MockForm - landscape width / height are reversed

### ISSUE THREAD

**Issue by Amerkashi** [mit-cml/appinventor-sources#1683]
Why are landscape width / height reversed? Was this logic intentional?

    PORTRAIT_WIDTH = width;
    PORTRAIT_HEIGHT = height;
    LANDSCAPE_**WIDTH** = **height**;
    LANDSCAPE_**HEIGHT** = **width**;

**Comment by ewpatton** [comment]
Assuming that you are referencing the configuration on lines [297-300 of MockForm.java](https://github.com/mit-cml/appinventor-sources/blob/897d96d396128b27df57293e4a51ac91b3eff0a4/appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockForm.java#L297), this was intentional. The `width` and `height` parameters represent the physical dimensions of the screen in portrait mode in this call. Therefore, the landscape values need to be swapped because it represents a 90º rotation of the screen.

**Comment by Amerkashi** [comment]
Yes, after further reviewing code, got it.
