### ISSUE TITLE
Add "Target Android SDK" information to Help > About menu

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1746]
Feature request from the power users: Add the target SDK supported by App Inventor to the Help > About dialog.

**Comment by bartmathijssen** [comment]
I think I made the correct changes to the source to solve this issue. If I am correct it will look like the following:

![Screenshot 2019-08-04 at 11 02 13](https://user-images.githubusercontent.com/25157850/62425281-631ab880-b6a7-11e9-9983-b6c4f9c6a334.png)

I unfortunately cannot test the code I wrote because I am currently working on my Chromebook. You can see the changes I made [here](https://github.com/bartmathijssen/appinventor-sources/tree/feature/target-sdk-information). 

If everything works when I get back home I will create a Pull Request with the changes.

**Comment by bartmathijssen** [comment]
I found a constant in Compiler.java named `TARGET_SDK_VERSION`. I thought I had the right idea by importing the `com.google.appinventor.buildserver.Compiler` package into TopToolbar.java, but that doesn't seem the work. I get the following error when building with ant:
```
[javac] /home/bart/Programming/bartmathijssen/appinventor-sources/appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java:9: error: package com.google.appinventor.buildserver does not exist
[javac] import com.google.appinventor.buildserver.Compiler;
[javac]                                          ^
[javac] /home/bart/Programming/bartmathijssen/appinventor-sources/appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java:790: error: cannot find symbol
[javac]           "<BR/>Target Android SDK: " + Compiler.TARGET_SDK_VERSION;
[javac]                                                 ^
[javac]   symbol:   variable TARGET_SDK_VERSION
[javac]   location: class Compiler
```

**Comment by ewpatton** [comment]
@bartmathijssen I think you were exploring this and you made the comment that shows as ghost. You would need to move the TARGET_SDK_VERSION into a common package (appengine doesn't depend on buildserver, so Compiler won't be available for import). Once you move the constant to a module that both appengine and buildserver depend on then you can do it this way. The most appropriate place is probably YaVersion.java.
