### ISSUE TITLE
About release versioning

### ISSUE THREAD

**Issue by jerry73204** [mit-cml/appinventor-sources#1817]
I noticed `v179` tag a few days ago. That would be a great convenience for me to find a _stabilized_ build. I would expect future stable releases follow this convention.

Since each AI2 build should pair up with correct AI2 companion version, Maybe we can plus the compantion version like `v179-XXX`, such that users have less trouble on finding correct version.

**Comment by ewpatton** [comment]
@jerry73204 Yes, the plan is that each release going forward from now will have a version tag that corresponds to `master` at the time the version was prepared. I'm not sure what the value is in the second half of your comment though. Who are "users" in this scenario? When we deploy App Inventor, we update the various companion URLs at the end of YaVersion.java, build the companions, place them into docs/companions/, and then build and deploy appengine. Anyone can get the most recent companion under Help > Companion Information. We do this for most of our test servers as well so that any new features we are trying have a corresponding companion available. Further, more than one release might correspond to the same companion version as they are versioned independently (but both monotonically increasing). Given all that, I'm not sure what the value would be in including the companion version number in the tag name. Do you have a specific scenario in mind?

**Comment by jerry73204** [comment]
To elaborate, in case devs or sponsors like CAVEDU would like to setup an AI2 mirror, the extra companion version gives us convenience that we don't need to check each commit to see the version number.

For example, Apache Kafka 2.12 has to be paired up with correct version of Scala 2.3.0. The release is denoted as 2.12-2.3.0.

**Comment by ewpatton** [comment]
That makes sense for when the dependencies are versioned independently (Kafka and Scala are two separately maintained projects with their own repos), but in our case the companion built at a given commit corresponds to that commit. The production version in the Play Store always is compatible with `master`. If you're not running the most recent version, then you will have to provide your own companion, which is built when you build the rest of the system anyway so it will match. Further, when @jisqyv does a release he makes a commit message with the companion version number in it; between those commits it does not change.

I guess I'm still not understanding why you need to look at each commit to check the companion version number.

**Comment by jerry73204** [comment]
Thanks your suggestion. I missed the commit message since my primary work was in early 2019. It's good that the versioning is made explicit.
In my point of view, the demand came from the fact the we maintain our patched AI2 release, and not always up-to-date to master. The commit message will give us more convenience to keep track of it. Thanks.

**Comment by ewpatton** [comment]
I'm going to close this because I think the discussion here is resolved. @jerry73204 Please reopen if I'm missing something.
