### ISSUE TITLE
Request: In asset upload, coerce bad characters in file names into good ones

### ISSUE THREAD

**Issue by marksherman** [mit-cml/appinventor-sources#184]
Instead of simply failing to upload, rename the file automatically during upload to become valid. 
For example: changing dashes and spaces to underscores. 

Solution may be related to #173 
@jisqyv

**Comment by halatmit** [comment]
@marksherman 
I suggest that we not do this.  It seems a little dangerous that you upload a file and then don't know exactly what name that file might be written under.   I know we could provide a mechanism to handle this, but I'll feeling conservative, and also feeling that we have too may open issues.  If you want to take ti on, go ahead.  But otherwise, let's just close it, OK?

**Comment by marksherman** [comment]
Ok with me. It was a common hitch-up point we saw in some middle schools,
but, yes, it does fail safely.

**Comment by halatmit** [comment]
Closing the issue

**Comment by halatmit** [comment]
Thanks.  I'll close this.




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty
