### ISSUE TITLE
Read-Only Textbox

### ISSUE THREAD

**Issue by aster94** [mit-cml/appinventor-sources#1841]
hello,

I am not sure if this is the right place where to do feature request, but in my opinion the ability to have read only text box would be useful

A workaround would be to use a label instead but in some cases a text box suits better

once it was asked: https://github.com/niteshmourya/app-inventor-for-android/issues/1971

**Comment by ewpatton** [comment]
@mit-cml/cornell-cs-5152-students-fall-2019 One of you might want to take a look at this.

**Comment by matthewcoufal** [comment]
@ewpatton Can I take this issue?

**Comment by ewpatton** [comment]
@matthewcoufal Sure. Please first test how Enabled works w.r.t. this and maybe investigate ways that others have done read-only text boxes on Android first. This will give us a good frame of reference before moving on to an implementation. For example, we might want to make it so that Enabled works correctly with large texts, or we might want to add a new ReadOnly flag that is less strict than the Enabled flag.
