### ISSUE TITLE
Length property (width/height) behaves differently in designer & runtime

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1862]
https://github.com/mit-cml/appinventor-sources/blob/33e6bd6640113e51f76fdefdd662251a7bdc00b8/appinventor/components/src/com/google/appinventor/components/runtime/AndroidViewComponent.java#L209

https://github.com/mit-cml/appinventor-sources/blob/33e6bd6640113e51f76fdefdd662251a7bdc00b8/appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidLengthPropertyEditor.java#L202

**Comment by ewpatton** [comment]
The code is correct. In the first case, it is checking for an error state (that `pCent` isn't in [0, 100]) and reporting it. In the second case, it's checking whether v is in [0, 100] so that it can set the value.

I guess there is a minor error in that the latter case uses `v > 0` rather than `v >= 0`, which would disallow for a component to have 0% width or height, but given that it would effectively make the component invisible I think it's okay. If one wanted that option in the designer they could switch to pixels and specify 0 there (or just set Visible = False).

**Comment by ColinTree** [comment]
The '0' is my point in this issue, although it does not actually bring any side effect.

**Comment by ewpatton** [comment]
I'd like to err here on the side of making the designer slightly more lenient rather than making the blocks slightly more restrictive. If for some reason someone is setting 0% width/height in the blocks, making it more restrictive will trigger an error where originally there wasn't one. If we allow for 0 in the designer, then it won't affect any existing projects since it wasn't something that could be done before. This also means that the change could be submitted against master rather than ucr as it wouldn't affect the companion behavior at all.
