### ISSUE TITLE
Make generic breaks on collapsed blocks

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1964]
**Describe the bug**

Using the Make Generic menu option on a collapsed block breaks the block and the undo stack.

**Affects**

- [ ] Designer
- [x] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**

Make Generic should properly update a collapsed block and the operation should be undoable with Undo command.

**Steps to reproduce**

1. Create a button
2. Create the Button1.Click event handler
3. Collapse the event handler
4. Right click on the block and select Make Generic
5. Attempt to interact with the block.

For examples see https://community.appinventor.mit.edu/t/a-problem-about-make-generic/1480?u=ewpatton

**Comment by shivanik6z** [comment]
I just reproduced the problem , it's still interactive(you can get component blocks)  but you can't expand it again. So we have to work on expand block functionality of the block which has been collapsed and made generic?

**Comment by BeksOmega** [comment]
This sounds like an interesting problem, but I feel like it needs a design decision so I wanted to post before working on it.

For solutions I can think of a few options:
1) Expand the block, modify it, and then collapse it again.
    This is the most visually appealing option, but it may lock up the interface because collapsing and expanding can be expensive. Testing this on the Blockly playground with the Spaghetti test blocks (one 3066 block stack) I got an average time of ~1120ms.
2) Change the "Make generic" option to an "Expand and make generic" option.
    This would expand the block and modify it, but not re-collapse it. It might be a good compromise between 1 & 3.
3) Disable the "Make generic" option if the block is collapsed.
    This is probably the simplest solution, but it's possible that it would be confusing for users.

There could be other options as well, those are just the three that sprung to mind.

I'm happy to work on whichever option sounds best to you guys!

**Comment by ewpatton** [comment]
Maybe a variant of 1: What happens if we call initSvg() and render() on the block after the Make Generic call?

Also, we have a mechanism in App Inventor's version of Blockly to only rerender a single block rather than the whole workspace. Using that will likely have better performance as changing the text on the collapsed block shouldn't force a rerender of the entire workspace.

**Comment by ewpatton** [comment]
@BeksOmega See [WorkspaceSvg.requestRender(block)](https://github.com/mit-cml/appinventor-sources/blob/c93be3f6203367bc94a4b641f08e2b964af25615/appinventor/blocklyeditor/src/workspace_svg.js#L1229)

**Comment by BeksOmega** [comment]
> Maybe a variant of 1: What happens if we call initSvg() and render() on the block after the Make Generic call?

Just tested this and it doesn't look like its going to work :/ First bad thing is that the renderDown() function doesn't re-render if the block if it is collapsed. Second bad thing is that Blockly's collapsing system is just weird. All of the inputs still exist, they're just not visible so they won't rerender.

Alternative suggestion (that is hopefully more efficient):
Refactor render() so that if the block is collapsed an updateCollapsed() or rerenderCollapsed() function gets called, instead of doing the normal render. This new function sets all inputs' visibility to false, and then calls toString() and updates the text on the collapsed-input.

This should be much better because toString is waaay faster. And we won't have to edit the "Make generic" function at all. Editing collapsed blocks will just work.

Not sure why I didn't think of this before. Hopefully I'm not forgetting something that I remembered earlier hehe. But I think it should work!

What do you think of that solution?

**Comment by ewpatton** [comment]
Are these updateCollapsed and rerenderCollapsed methods functions that you are proposing to add, or are they in a newer version of Blockly (keep in mind we are 3 years behind at this point).

**Comment by BeksOmega** [comment]
> Are these updateCollapsed and rerenderCollapsed methods functions that you are proposing to add, or are they in a newer version of Blockly (keep in mind we are 3 years behind at this point).

These are functions I'm proposing. But I do think that if it works these would be a great thing to push back to core. It would be really nice be able to edit collapsed blocks without having to expand them first.

**Comment by ewpatton** [comment]
@BeksOmega Also take a look at renameCollapsed in blocklyeditor/src/utilities.js. It's responsible for updating the names of variables inside of collapsed blocks. We might be able to repurpose it or write a similar method that can be used in this case. I think it's essentially the combined functionality of your two proposed functions. What do you think?

**Comment by BeksOmega** [comment]
> Also take a look at renameCollapsed in blocklyeditor/src/utilities.js.

So I did look at renameCollapsed! But before I talk about that I wanted to back up and redux what I said before, because I did a bad job communicating the first time.

So the rough idea is to change rendering to work like this:
1) Everything is the same until renderHere.
2) If the block is collapsed an updateCollapsed_() function is called at the beginning of renderHere
3) This function updates the collapsed string & hides any new inputs/icons so the block is ready to be rendered.
4) Rendering continues as normal.

What's great about hooking the fix to the render call is that it works automatically. -- That's the one problem I see with the other method, that you have to remember to call it.

... I may have also done a bit of sneaky coding and it seems to work well:
![MakeGeneric](https://user-images.githubusercontent.com/25440652/75001852-65f8b300-5417-11ea-8d78-449d10cad044.gif)
You can check out my branch [here](https://github.com/mit-cml/appinventor-sources/compare/master...BeksOmega:feat/update-collapsed-2). As you can see, it works even though I didn't touch the component blocks at all.

I'm totally cool with doing it the other way, I just think this might be a bit more future proof.

Would you be willing to look at a PR for this after I do a bit more testing? Or should I give repurposing renameCollapsed a shot?

**Comment by BeksOmega** [comment]
Giving this the gentlest of bumps.

I won't bump this anymore, I just realized I forgot to @ewpatton on the above, so I wanted to rectify that =)

**Comment by ewpatton** [comment]
@BeksOmega That sounds like a reasonable approach. Do you want to make a first pass at implementing it?

**Comment by BeksOmega** [comment]
> @BeksOmega That sounds like a reasonable approach. Do you want to make a first pass at implementing it?

I would love to @ewpatton ! Here's an initial list of things I need to do before creating a PR:

- [ ] Fix icons getting reopened when the block is expanded.
- [ ] Incorporate your toString optimization from #2048 
- [ ] Do speed tests to ensure this is efficient.
- [ ] Write unit tests? - I would love to write unit tests but I'm not sure how to do that within the current framework.

And if it works out I'll push my changes back to core as well.

**Comment by ewpatton** [comment]
@BeksOmega We are definitely interested in expanding unit test coverage, so anything you can offer here is helpful.
