### ISSUE TITLE
A dictionary get from dictionary in foreach block was converted to Alist unexpectedly.

### ISSUE THREAD

**Issue by wxbit** [mit-cml/appinventor-sources#2087]
**Describe the bug**

A dictionary get from dictionary in foreach block was converted to Alist unexpectedly.
![image](https://user-images.githubusercontent.com/3827464/76157155-0b15ca00-6140-11ea-8ed0-f22b1a5e773a.png)

**Affects**

- [ ] Designer
- [ ] Blocks editor
-  Companion
-  Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

#2019 #2026 

**Expected behavior**

**Steps to reproduce**

**Comment by BeksOmega** [comment]
Interesting, thank you for filing! I would like to give this a look if no one else is interested. Now I get to learn how the typing system works!

**Comment by wxbit** [comment]
I don't know if it's going to cause other problem.

![image](https://user-images.githubusercontent.com/3827464/76199892-a20b8080-622b-11ea-82f5-53c09419e7cb.png)
![image](https://user-images.githubusercontent.com/3827464/76200012-d5e6a600-622b-11ea-9a40-2674302248d0.png)
![image](https://user-images.githubusercontent.com/3827464/76200032-df700e00-622b-11ea-919e-9aae4c5b2fee.png)

**Comment by ewpatton** [comment]
I think it is safe to turn off the recursive option here. The design was so that alists and dictionaries could interoperate such that anywhere you could use an alist a dictionary could also be used, and vice versa. It might  have been premature (and costly) to rewrite the entire dictionary structure recursively into a list. We could just transform the topmost element as passing a nested dictionary to a list operation will invoke this code again and we don't necessarily want to lose the fact that it is a dictionary when passed to dictionary code.

**Comment by ewpatton** [comment]
Fixed by #2091
