### ISSUE TITLE
Make a list with text (string) blocks failed to save string values

### ISSUE THREAD

**Issue by xuwenbin** [mit-cml/appinventor-sources#2205]
**Describe the bug**

The value(s) of "Text (string)" block in "Make a list" are not saved.

**Affects**

- [ ] Designer
- [*] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Strings typed in should be saved and restored after project is reopen.

**Steps to reproduce**

1. Drop a "Make a list" block onto designer
2. Drop several "Text (string)" blocks onto designer and connect to "Make a list"
3. Typed in string (any letters, numbers, etc.) in each "Text (string)" block
4. Clicked "My Projects" -> "Save project"
5. Signed out
6. Signed in and open the same project
7. Looked at designer
8. Noticed that "Make a list" -> "Text (string)" blocks are empty

<img width="621" alt="Screen Shot 2020-06-08 at 13 58 06" src="https://user-images.githubusercontent.com/19218275/83997233-829e0400-a990-11ea-9f70-b6e498bf7601.png">

**Comment by PeterMathijssen** [comment]
Hi @xuwenbin 

I did just as you described but for me the strings are saved. 
![Selection_999(1260)](https://user-images.githubusercontent.com/32273650/84010408-e3b7de80-a974-11ea-8918-77600020d30d.png)

Can you tell what version of App Inventor you are using? 
http://ai2.appinventor.mit.edu/
http://code.appinventor.mit.edu/

Can you post an aia that shows this behavior?

**Comment by xuwenbin** [comment]
What browser are you using?
- Google Chrome Version 83.0.4103.97 (Official Build) (64-bit)

Can you tell what version of App Inventor you are using?
- I downloaded, complied and ran AI2 (the latest code) in my own Ubuntu server

Can you post an aia that shows this behavior?
- See below

**Comment by PeterMathijssen** [comment]
I tried your aia and followed the steps you took. Still working for me.

**Comment by conorshipp** [comment]
So... this is the same issue that we had at Kodular.

Here's what I found out after a bit of sleuthing:

After editing the text of a text block, you get an NPE in the Chrome Console. Once this NPE happens, all sorts of weird behaviour can be observed in the blocks editor.
![image](https://user-images.githubusercontent.com/25845449/84019848-c5a0ad00-a979-11ea-99e8-b9a428a7ace8.png)

The NPE is occurring here
https://github.com/mit-cml/appinventor-sources/blob/ae1488696407a0e88f8e849fbec47ebc15969b41/appinventor/blocklyeditor/src/blocks/text.js#L44

More specifically `otherTypeArray` is null.
![image](https://user-images.githubusercontent.com/25845449/84020518-d998de80-a97a-11ea-85b1-31f958c3ea5d.png)

After reverting the changes made in #2177 the problem seems to be resolved.

cc: @BeksOmega

**Comment by BeksOmega** [comment]
Thanks for the ping @conorshipp ! Looks like an easy fix. I should be able to get a PR up today :D

**Comment by xuwenbin** [comment]
@BeksOmega @conorshipp thanks for the efforts. Am I supposed to get the fix in main trunk once you finish the PR?

**Comment by BeksOmega** [comment]
@xuwenbin It should be merged into the `master` branch, and then you'll be able to pull it :D

**Comment by xuwenbin** [comment]
Roger that, great thanks!
