### ISSUE TITLE
Block that takes a list of substrings and a string, then returns a list of substrings found in the string

### ISSUE THREAD

**Issue by BeksOmega** [mit-cml/appinventor-sources#2288]
**Describe the desired feature**

From @PeterMathijssen [here](https://github.com/mit-cml/appinventor-sources/pull/2286#issuecomment-675895730):
>I was wondering, with the "contains any block" you get a true if any of the pieces of text in the list is found. In my example the textbox is filled with "a".
>
>![](https://user-images.githubusercontent.com/32273650/90602609-53aad680-e1fa-11ea-840c-edaca846a884.png)
>
>Would it be an idea to also be able to get information on what piece(s) was/were found using this block else you would have to make something like this
>
>![](https://user-images.githubusercontent.com/32273650/90603151-21e63f80-e1fb-11ea-900e-725c7ca611a7.png)
>
>Or even more complex if you want to collect all the pieces found.

**Give an example of how this feature would be used**

To be provided by @PeterMathijssen

**Why doesn't the current App Inventor system address this use case?**

This can be implementing using a procedure block, but it requires looping over a list, adding to a list, the contains block, etc. Which is quite complicated for younger users.

**Why is this feature beneficial to App Inventor's educational mission?**

For younger users, this gives the power of the procedure implementation as a single block.

**Comment by BeksOmega** [comment]
I think this is an interesting idea, but my one concern is how to represent this within the blocks language. Should it be added to the contains block as another option? Or should it be its own block? If it is added as an option, what would the display text be?

Once those things are figured out, it shouldn't be difficult to add (if desired).

**Comment by PeterMathijssen** [comment]
Hi @BeksOmega 

**Usecase 1:**
Well i just thought of a practical case. Just say you want a user to type in a sentence during a quiz, and in that sentence you expect to find a number of words to indicate if a user has acquired the knowledge needed to proceed. 

![image](https://user-images.githubusercontent.com/32273650/90713354-67f7dd80-e2a5-11ea-9855-225b705d02de.png)

With the contains any block you can return for instance a list and calculate a score for the student. 

![image](https://user-images.githubusercontent.com/32273650/90713554-dc328100-e2a5-11ea-9e7c-f0c01dc73565.png)

Is the list empty or has a length of 0 the student didn't produce any of the required words. 

Has for instance the student produced all 5 words he scores 100 percent. For every word he misses he looses 20% percent. This is easy to calculate this way. 
![image](https://user-images.githubusercontent.com/32273650/90713905-b5c11580-e2a6-11ea-89ba-5ecb836c3e27.png)

So it would have to be possible to combine these blocks. 

**Usecase2:**

You have a set of forbidden words in a textbox. Because the contain any block returns what word is found in the textbox you can easily display a notifier with a message containing that a certain word the user typed was not allowed.

**Comment by PeterMathijssen** [comment]
I was thinking if this block could also be part of the contain family. What if we have another option in the dropdown menu called "contains any, return as list"?

**Comment by halatmit** [comment]
Peter,

Those are good exampl, but I'd rather leave things so that contains (and
variants) return booleans.
What we're missing in App Inventor is a filter operation, as in Lisp or
Python.   So, for your example,
we would take the list of words (civil, war, slavery, ...) and filter it to
return the words that the sentence
contains.
We've been working on (and prototyping) the set of map, filter, reduce
operations, and we're planning on adding them
(no ETA yet).  I'd rather go this route for the kind of application you are
describing.

== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by halatmit** [comment]
As I wrong above, I'd rather do this sort of thing with a filter operation.


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by PeterMathijssen** [comment]
Hi Hal,

Thank you for your comment. I educated myself on the concept of filtering 
https://en.wikipedia.org/wiki/Filter_(higher-order_function)
And that is exactly what i was talking about. Would be great if we could do that for numbers and strings. 

Peter

**Comment by halatmit** [comment]
We'll try to get this into App Inventor (also map and reduce).

== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by ewpatton** [comment]
This was released in nb185.
