### ISSUE TITLE
Deploy in Google appengine

### ISSUE THREAD

**Issue by znyrpavithra** [mit-cml/appinventor-sources#2422]
your-appengine-SDK-folder/bin/appcfg.sh -A <your-application-id> --oauth2 update appinventor/appengine/build/war.
   In the above command, which folder is referred to as "your-appengine-SDK-folder"?

**Comment by ewpatton** [comment]
appcfg.sh is no longer supported by Google. You should switch to using `gcloud app deploy` instead (see Launch the server in [this document](https://docs.google.com/document/d/1JvexwXOQ4wW2Cccfyq3z83fXklP7Ob_1jPmMdxsv8WM/pub)). In the future, please ask clarifying questions in the open source community rather than opening an issue.
