### ISSUE TITLE
Drag and drop projects doesn't work if autoload is off

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2433]
**Describe the bug**

Dragging an AIA from the user's machine to the project list does not appear to work when autoload is off, at least until one project is opened. Once a project has been opened, if you go back to the project list, you can drag and drop an AIA to upload it. This functionality should be available as soon as the project list is loaded, regardless of whether autoload is enabled or not.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [x] Other... (please describe) Project list

**Expected behavior**

As soon as the project list is visible, the user should be able to drag and drop an AIA in the window to load it.

**Steps to reproduce**

1. Turn off autoload in the settings menu.
2. Reload the page.
3. Drag an AIA from your computer to the window.

You should get the "Drop to upload" green outline, but it won't appear. If you then open a project and go back to the project list and try again, it will work as expected.

**Comment by Himanshu2107** [comment]
If autoload is off, it is also the case that projects cannot be exported until atleast one is open, as described in issue #2419. These two issues might be related and fixing code related to autoload might fix both.

**Comment by ewpatton** [comment]
@Himanshu2107 That could be a possibility. Is this something you'd be interested in investigating?

**Comment by ewpatton** [comment]
For this bug, the most relevant part of the code would be the Java code that finds the relevant target in com/google/appinventor/client/utils/HTML5DragDrop.java

**Comment by Himanshu2107** [comment]
> @Himanshu2107 That could be a possibility. Is this something you'd be interested in investigating?

Yes, for sure!


> For this bug, the most relevant part of the code would be the Java code that finds the relevant target in com/google/appinventor/client/utils/HTML5DragDrop.java

Thanks, that helps.

**Comment by Himanshu2107** [comment]
The cause of this bug seems to be same as that of #2419. The relevant java code in com/google/appinventor/client/utils/HTML5DragDrop.java (shown below) checks for if the `currentView` is set to `PROJECTS` or `DESIGNER`.
```
protected static Element shouldShowDropTarget(Element target) {
    if (Ode.getInstance().getCurrentView() == Ode.PROJECTS) {
      boolean noProjects = 0 == ProjectListBox.getProjectListBox()
          .getProjectList().getMyProjectsCount();
      while (target != Document.get().getBody()) {
        if (noProjects && target == Ode.getInstance().getOverDeckPanel().getElement()) {
          // If there aren't any projects, then we want to support dropping into the empty space
          return Ode.getInstance().getOverDeckPanel().getElement();
        } else if (target == ProjectListBox.getProjectListBox().getElement()) {
          // Allow dropping into the project list
          return target;
        }
        target = target.getParentElement();
      }
    } else if (Ode.getInstance().getCurrentView() == Ode.DESIGNER) {
      while (target != Document.get().getBody()) {
        if (target == AssetListBox.getAssetListBox().getElement()) {
          return target;  // Media list is a drop target
        } else if (target == PaletteBox.getPaletteBox().getElement()) {
          return target;  // Palette panel is a drop target (for extensions)
        }
        target = target.getParentElement();
      }
    }
    return null;  // No valid drop target
  }
```
Now as the view is initialized to `DESIGNER` in (Ode.java) the if condition  
`if (Ode.getInstance().getCurrentView() == Ode.PROJECTS)`
seems to be failing when autoload is off and we have not selected any projects (refer to https://github.com/mit-cml/appinventor-sources/issues/2419#issuecomment-797777953 for details). I was not able to confirm this although. The code did not pause in the debugger. With the SuperDevMode On the target did not appear at all. No matter if autoload was selected or not. . 

But nevertheless, the problem does seem to be originating from the same source as in #2419, i.e. in 
com/google/appinventor/client/Ode.java where the `currentView` is initialized to `DESIGNER`.

So fixing #2419 may fix this issue as well.
