### ISSUE TITLE
Wrong scaling of line width for canvas

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#2517]
**Describe the bug**

This was observed on the phone.  I have not tried is on a tablet or the emulator.   This might be different with a different screen size.

**Affects**

- [ x] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Canvas line with should be what it's set to when the component is created in the designer.

**Steps to reproduce**

Create an app that has a single canvas, whose line with is specified as 2.  Try the app in the companion running on the phone.   If I examine the line-width property, I get 0.72727, not 2.

**Comment by preetvadaliya** [comment]
@halatmit, sir I got the problem.

the problem is basically with **paint.setStrokeWidth()** method, this method set line width in a pixel unit and when we performed do it on getter block then it will divide results by device density [see this](https://github.com/mit-cml/appinventor-sources/blob/ce385622ff1ab810df4f3e6bd0200a80574fc171/appinventor/components/src/com/google/appinventor/components/runtime/Canvas.java#L1196).

and when we set line width it will multiply the value with the device density and then set to the **paint** object. [see this](https://github.com/mit-cml/appinventor-sources/blob/ce385622ff1ab810df4f3e6bd0200a80574fc171/appinventor/components/src/com/google/appinventor/components/runtime/Canvas.java#L1208)

but the problem has occurred only for the defaultValue of line width because we forgot to multiply it with the screen density [see this](https://github.com/mit-cml/appinventor-sources/blob/ce385622ff1ab810df4f3e6bd0200a80574fc171/appinventor/components/src/com/google/appinventor/components/runtime/Canvas.java#L765)
