### ISSUE TITLE
Fix bug in clock documentation / methods

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#290]
From Emily

While I was using AI2 with services, I noticed a mistake in the documentation for the Clock sensor component:

In MakeInstant(text from), the documentation says the instant is specified as "MM/DD/YYY hh:mm:ss or MM/DD/YYYY OR hh:mm", when I think it  means to say "MM/DD/YYY hh:mm:ss or MM/DD/YYYY hh:mm” — I looked online, and there are a few users who are having problems using this method because they are confused about the format of the input.

Similarly, I think there are some methods where the output format could be clarified, namely FormatDate and FormatDateTime. Because other methods ask for the date as MM/DD/YYYY, users may think that the FormatDate and FormatDateTime have an output in that format, when that is not the case.

Additionally, there should probably be a method that actually does return the date and time as MM/DD/YYYY hh:mm:ss. This would help users make apps with services because it would be easier to get an instant corresponding to a certain date and time — for example, they could easily make a task launch a notification on a certain date at a certain time.

**Comment by halatmit** [comment]
assign to Grace Ryu

**Comment by graceRyu** [comment]
I would like to focus on this part of the issue: 

“Similarly, I think there are some methods where the output format could be clarified, namely FormatDate and FormatDateTime. Because other methods ask for the date as MM/DD/YYYY, users may think that the FormatDate and FormatDateTime have an output in that format, when that is not the case.”

I am thinking to modify FormatDateTime and FormatDate methods so that they can both output 05/20/2015 and May 20, 2015. This can be done by adding a second parameter(format).  e.g. FormatDateTime(instant, format), FormatDate(instant, format), where the second parameter (format) specifies whether it should be MM/DD/YYYY or May 20, 2015.

**Comment by halatmit** [comment]
I'm closing this because #405  was closed.
