### ISSUE TITLE
Need to create default initial value for Spinner

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#309]
See this thread https://groups.google.com/forum/#!category-topic/mitappinventortest/Q2f0fyPsVk8

the user currently has to set the spinner selectionindex to a value (for example 1) to be able to do some data validation
probably a default value = 1 could be set automatically by App Inventor, in case the user forgot to do this?

**Comment by EnisM** [comment]
My workaround for this was to create a dummy first item in the list... "Select Item..."

Then, when I do anything with the list, I check to make sure the selectionindex is > 1.

**Comment by ReachAayush** [comment]
Hello, I was looking to fix this as I am also tackling issue #211. 

I was thinking that a possible solution would be to set the "String selection" to the empty string when the Spinner is created. Currently the selection string is null until a user selects something, which seems inconsistent with the fact that the default SelectionIndex is 0 if nothing is selected.

Please let me know if this workaround will not work.

**Comment by EnisM** [comment]
Personally, I think initial selection has to be the first item.

In my case, I worked around this by adding a dummy "Select..." item at the
top of the list, and then in processing, I check the selectionindex, which
oddly enough always starts out as 1 even though the value is null, and if
selectionindex = 1 then put up an error message.

Ideally, the thing should have the first item selected, but that doesn't
trigger the AfterSelecting because a TRUE selection hasn't been made.  But
at least that way, at minimum if there's no user interaction, the first
item is the value that's returned.

A lot of people got tripped up by this because they put all of the stuff to
do for a selection in the AfterSelecting, which just doesn't trigger.  But
if they know that the first one is always selected automatically even if
there's no user interaction, they can provide the proper default settings
in their code to pertain to the first selection, without the AfterSelecting
getting triggered.

Either way, it's a tough call...

**Comment by puravidaapps** [comment]
the default SelectionIndex is 0, so yes, empty string would be fine for
the default Selection imho
Taifun

Am 12.03.2015 um 17:38 schrieb EnisM:

**Comment by halatmit** [comment]
#354 was closed

**Comment by militrik** [comment]
Set "spinner selection index"=0 is not worked.
It always select first item from the list. And  "spinner selection index" =1 select first item from the list too.
Because of this, it is impossible to trigger the first element with Spinner.AfterSelecting
![01](https://user-images.githubusercontent.com/12719705/27949783-a3b61fc4-6307-11e7-9682-34179c657578.jpg)
