### ISSUE TITLE
Update the App Inv documentation on debugging

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#378]
http://appinventor.mit.edu/explore/learn/live-development-testing-and-debugging.html

The part about the Java system log is about AI classic.   Update it for AI2 and talk about Javascript.

**Comment by e40614** [comment]
I want to update the documentation.
But I don't know how to share my modification.

Is it correct?
1.Download "live-development-testing-and-debugging.html" in the docs/learn
2.Make some modifications
3.pull request(Comparing shows that there are 48 files change,because I download all the web page.)
I think this method is a little strange.

**Comment by halatmit** [comment]
@e40614 
Thanks for offering to update the documentation.   We don't use pull requests for this.  Instead, make comments and suggested edits in this Google doc:

https://docs.google.com/document/d/1BeLh_HKtVwmphKZZJyemtr8x5j1whLD8V4v6-QHj8TE/edit#heading=h.tav27sktyepa

That doc is not linked into the App Inventor site yet, but it will be when we do the next release.
== Hal

**Comment by halatmit** [comment]
#384

**Comment by jisqyv** [comment]
#384 is now merged and should be in this afternoon's release
