### ISSUE TITLE
Image picker does not see the pictures taken by the camera

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#433]
These images are in 
The image is stored at  file:///storage/emulated/0/Pictures/
The image picker does seem to see that directory. 
From Ralph:

Our teachers and I just noticed  that there's an apparent disconnect between the Image Picker and the Camera components.   If you take a picture with the Camera component, there seems to be no way to retrieve that picture from your device by using the Image Picker.  On my device the Image Picker gives me access to the following folders:

    Camera (pictures taken with the device's camera -- but not in App Inventor)
    assets -- Assets loaded onto the device by App Inventor apps
    Screenshots 
    ProjectData (seems empty or inaccessible on my device)

The image is stored at  file:///storage/emulated/0/Pictures/

It seems like it should be possible to retrieve images taken by an app using Image Picker from that folder??   Should I post an issue on this?  Or am I missing something?

**Comment by graceRyu** [comment]
Hi Hal,
 
It turns out that a default media contents provider(e.g. Gallery, Google Photos) has to go through scanning to recognize newly added pictures or files. The disconnection between ImagePicker and Camera component was caused because the scanning was not occurred immediately. (In other words, if you wait long enough, the pictures taken by Camera component show up eventually. ) 

To make the pictures from Camera component available right away, the scanFileToAdd method will be called so that the image taken by Camera will be scanned into the default media contents provider. 

![screen shot 2015-07-01 at 11 21 33 am](https://cloud.githubusercontent.com/assets/8516676/8458213/c7bb2a36-1fe3-11e5-9305-119193992439.png)

![screen shot 2015-07-01 at 11 20 43 am](https://cloud.githubusercontent.com/assets/8516676/8458122/3f2bb460-1fe3-11e5-87e8-9506c188544d.png)

Pull Request: #444

**Comment by halatmit** [comment]
#444 was merged
