### ISSUE TITLE
`&` in AppName causes apk build failure

### ISSUE THREAD

**Issue by fmntf** [mit-cml/appinventor-sources#456]
If Screen1.AppName contains `&`, the apk build fails with:

`WARNING: YAIL compiler - AAPT execution failed.`

Should we prevent users to put characters like `&` in AppName? Are there other characters not allowed?

**Comment by halatmit** [comment]
Could you send a specific example of how to create this error?   App Inventor already has a check to remove ampersands in project names, but I guess we need more checks.  I'd like to see where they are missing.

**Comment by fmntf** [comment]
Create a new project. In Designer, type (or copy/paste) in Screen1.AppName "foo & bar".
The ampersand is not removed.

**Comment by weihuali0509** [comment]
I am looking into that.

**Comment by weihuali0509** [comment]
I can confirm the symptom - build failed when the app name contains the *&*, ampersand. 

After several intense debugging session, I found out there is no problem in the implementation, but rather a bug in the android *aapt*.  An ampersand in the name string breaks AAPT and other places in Android. 

This bug is also described in this Java file, line 300
https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java

I am going to follow the same style to fix this problem - by replacing the *&* with the word *and*.

@halatmit

**Comment by kkashi01** [comment]
You can use &amp; also

**Comment by halatmit** [comment]
#464 was closed
