### ISSUE TITLE
Setting the background color on a button changes the height

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#479]
I created a project that had a button.   The button height was 48.
Then I set the background color.  The button height changed to 38.

**Comment by liyucun** [comment]
Hi Hal, I tried your way but not able to reproduce that problem.

**Comment by halatmit** [comment]
@liyucun What was the button height before you set the background color, and what was it afterward?  This migth be messier than it seems.  But let's at least see if you are seeing the same behavior.  But also, there are more important issues to work on.

**Comment by E-Hon** [comment]
I can't reproduce it either.

I started an empty project, dragged a button, set the height to 48 pixels, changed background color. The height was still 48 pixels.

I tried to add a label so that when the button is clicked, it shows the button's height. Then I set the height to 48 pixels and then changed the background color. The label didn't change

**Comment by halatmit** [comment]
@E-Hon @josmas @liyucun 
I'm closing this one.   Thanks to everyone for checking.
