### ISSUE TITLE
Button font size reported incorrectly

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#520]
Create an app with a single button.   the (defaut) test font size is 14.   but if you read the size, it's reported as 28.   It looks like this is off by a factor of 2 in general.
doesn't seem to matter whether this is fixed or responsive sizing.

**Comment by Momoumar** [comment]
@halatmit,
The issue is that we use  [```public float getTextSize()```](http://developer.android.com/reference/android/widget/TextView.html#getTextSize()) to get the fontSize of a TextView which is returned in **px(pixel)** . On the other side we use [``` public void setTextSize (float size)```](http://developer.android.com/reference/android/widget/TextView.html#setTextSize(float)) which sets the fontSize of a TextView in **sp(scale-independent pixel)** Note that sp = K*px. Thus, depending on the device, we have that ratio K. For instance in mine the K = 3.
And this is the case for all components that has a fontSize property not only the Button.
We have two solutions:
* Set the size of the TextView using pixel unit.
* Convert the px returned by ```public float getTextSize()``` to sp (The one I would suggest, seeing that AI users are used to setting fontSize using sp without knowing)

**Comment by halatmit** [comment]
@Momoumar 
That great that you've figures this out.   I agree with using the second solution.  the key thing is that if the user sets the size to X, then reading the size should produce the same X.

Can you go ahead and make the changes?

**Comment by Momoumar** [comment]
Yes I will.

**Comment by halatmit** [comment]
#542 was closed
