### ISSUE TITLE
Signal error when importing out of date extensions

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#579]
Warn users when they use extensions (e.g., import aix files) that no longer work do to changes in App Inventor.

**Comment by ewpatton** [comment]
I'm not sure we can realistically support this in the long term. At the moment, we do not embed any information about the current build of App Inventor into extensions. Assuming we did, extensions authors might need to rebuild their extensions for every new release of App Inventor which may not be feasible. Further, just because we release a new version does not imply it breaks extensions published with the previous version. Since this issue was raised we have added a field for extension authors to specify a minimum Android SDK version to provide a floor for extensions so I think we can close this issue for now.
