### ISSUE TITLE
Problems with videoplayer seek- to

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#582]
see thread at 

https://groups.google.com/forum/#!category-topic/mitappinventortest/bhrTMzmfQs4

**Comment by jisqyv** [comment]
This can easily be an issue with the particular asset. I have seen broken mp4's in other contexts that exhibit similar behavior.

**Comment by E-Hon** [comment]
Hi guys, 
Our code doesn't have any problem.

The intervals used by that user are just too small that `seekTo()` doesn't work. I wrote a native android app with ![this video](http://www.sample-videos.com/video/3gp/240/big_buck_bunny_240p_1mb.3gp) to test how large an interval needs to be in order to "jump" to next scene. And it took around 500ms to do so. 
_(for some reasons, emulators can't play mp4 files so I tried a 3gp)_

I came across this before. It's because `seekTo()` can only jump to ![keyframes](https://en.wikipedia.org/wiki/Key_frame) and each keyframe occupies a certain amount of time (probably depending on the compression format). And this amount of time is not as small as few milliseconds.

I haven't tried it but I think audio files can do better but our Player component doesn't have `seekTo()` for user

**Comment by halatmit** [comment]
Ethan, thanks!
I updated the documentation 
PR #694

**Comment by wadleo** [comment]
Hi @halatmit, from the discussion above looks like this bug has been resolved and the PR merged but the issue is still open, thanks and waiting for your reply.

**Comment by halatmit** [comment]
@wadleo 
Thanks fro catching this.
Closing.
