### ISSUE TITLE
eclipse for appinventor(some error)

### ISSUE THREAD

**Issue by Lemniscate317** [mit-cml/appinventor-sources#619]
I think i can ask some question in there.
and also i dont know how to use git
the question is that:
I follow the steps to import the appinvenor-sources into the eclipse.and i found some error in it.
i want to know how to fix it .
follow is the details.

Description	Resource	Path	Location	Type
The method copy(File, OutputStream) in the type Files is not applicable for the arguments (new InputSupplier<InputStream>(){}, File)	ProjectBuilder.java	/appinventor-sources/appinventor/buildserver/src/com/google/appinventor/buildserver	line 250	Java Problem
The method newInputStreamSupplier(URL) is undefined for the type Resources	Compiler.java	/appinventor-sources/appinventor/buildserver/src/com/google/appinventor/buildserver	line 1210	Java Problem
The method setServiceAccountScopes(Collection<String>) in the type GoogleCredential.Builder is not applicable for the arguments (String)	FusiontablesControl.java	/appinventor-sources/appinventor/components/src/com/google/appinventor/components/runtime	line 861	Java Problem
The type AIAsset is already defined	AIAsset.java	/appinventor-sources/appinventor/aimerger/src/edu/mills/feeney/thesis/aimerger	line 10	Java Problem
The type AIMerger is already defined	AIMerger.java	/appinventor-sources/appinventor/aimerger/src/edu/mills/feeney/thesis/aimerger	line 47	Java Problem
The type AIProject is already defined	AIProject.java	/appinventor-sources/appinventor/aimerger/src/edu/mills/feeney/thesis/aimerger	line 20	Java Problem
The type AIScreen is already defined	AIScreen.java	/appinventor-sources/appinventor/aimerger/src/edu/mills/feeney/thesis/aimerger	line 10	Java Problem
The type CheckBoxList is already defined	CheckBoxList.java	/appinventor-sources/appinventor/aimerger/src/edu/mills/feeney/thesis/aimerger	line 18	Java Problem

i am  sorry idont know how to make it clean to see.

**Comment by josmas** [comment]
Hi there,

the AI Merger is a separate project so it should not be included in
Eclipse. If you want to work with the merging utility, you should import it
as a separate project.

The instructions for Eclipse were written before the merger was placed in
the main repo, so they are a bit out of date. Most people use IntelliJ
instead, which imports the projects in a cleaner way, but if you want to
help bringing the Eclipse instructions up to date, that would be great (you
are going to have to do some experimenting though). We recommend IntelliJ
because it has the same interface that Android Studio has, but Eclipse
should work too.


cheers,
José

**Comment by Lemniscate317** [comment]
thanks for your answer.
my english is poor.
i just want to add some block by using the inner method.(like using the bluetooth method to translate some data and i make them to a method).i want to ask the error will affect my project? because i cant understand what you said about the AI Merger is what.

**Comment by josmas** [comment]
Hi again, you won't have any issues as long as you use ***ant*** from terminal to compile. You won't be able to compile with Eclipse.

**Comment by Lemniscate317** [comment]
thanks very much!!!!
