### ISSUE TITLE
change "obsfucate" to obfuscate

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#641]
fix misspelling

**Comment by halatmit** [comment]
@fturbak 
I'm working on this but need help from Lyn on what to put in versioning.js

**Comment by marksherman** [comment]
Trying to help, here are the instances of it in source code (instances in post-build files removed).
The fact that there is generator code changing yail primitives... There's some (hopefully logical) speculation below.

The very last line I missed at first. It is the actual runtime.scm, so that must be the function that the generators refer to. Neither of these, the generator, nor the runtime, change the block code (pre-generator), so I don't think they need a versioning.js upgrade path. The project won't notice.

As for the ones in the middle, the names of the message variables are wrong, but *the calls to those don't appear in the search.* So it may be possible that the code is looking for those messages variables spelled correctly, and not finding them. If that's true, they also can be changed without a version update, because the blocks were doing it right the whole time. 
```
blocklyeditor/src/generators/yail/text.js:  // Deobsfucate the TEXT input argument
blocklyeditor/src/generators/yail/text.js:  var code = Blockly.Yail.YAIL_CALL_YAIL_PRIMITIVE + "text-deobsfucate"
blocklyeditor/src/generators/yail/text.js:  code = code + Blockly.Yail.YAIL_DOUBLE_QUOTE + "deobsfucate text"
blocklyeditor/src/msg/en/_messages.js:    Blockly.Msg.LANG_TEXT_TEXT_OBSFUCATE_HELPURL = 'http://appinventor.mit.edu/explore/ai2/support/blocks/text#obsfucatetext';
blocklyeditor/src/msg/ko_kr/_messages.js:    Blockly.Msg.LANG_TEXT_TEXT_OBSFUCATE_HELPURL = 'http://appinventor.mit.edu/explore/ai2/support/blocks/text#obsfucatetext';
blocklyeditor/src/msg/ru/_messages.js:    Blockly.Msg.LANG_TEXT_TEXT_OBSFUCATE_HELPURL = 'http://appinventor.mit.edu/explore/ai2/support/blocks/text#obsfucatetext';
buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm:(define (text-deobsfucate text confounder)
```

**Comment by marksherman** [comment]
Linking in the discussion between @fturbak and @halatmit from the email list:
https://groups.google.com/forum/#!msg/app-inventor-dev/nVL6DuYhbjs/y375JBRyAwAJ

**Comment by halatmit** [comment]
#647 was closed
