### ISSUE TITLE
Image sprites are not scaled correctly in the designer

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#653]
See Ghica's note:

https://groups.google.com/forum/#!category-topic/mitappinventortest/FDEEx9PYyF0

The problem is both with images and image sprites, although they are slightly different.
In all cases, the phone works correctly.  It's the designer that's not scaling the image.   And there are 
different results for images depending on whether you select Scale Picture to Fit.

**Comment by E-Hon** [comment]
Hi @halatmit , 
The scaling behavior of Image and ImageSprite is very unpredictable. I will try list it below.

If you try to increase the width or height of a picture to a value more than its preferred/automatic/original one, the behavior is like scale to fit even though ScalePictureToFit is unchecked. After refreshing the page, that Image goes back to its preferred dimensions but the frame remains the same. At this point, if you further change the height or width, it either scales proportionally or scales to fit. I don't know what governs it. 

Should I also fix this or should I stick to what this issue describes? 

I don't know the behavior of unchecking ScalePictureToFit. Is it scale proportionally or do not scale? I suggest we change to use a dropdown list with ScalePictureToFit, ScaleProportionally and DoNotScale so that any change in height or width will base on the selected option

**Comment by halatmit** [comment]
Do whatever seems reasonable.  But make sure:

- It's reasonably compatible with what happens on the phone.
- It works with both fixed and responsive scaling.
- There's a smooth upgrade path for older projects. (If you change
scalePictureToFit

Thanks!!!


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by E-Hon** [comment]
some updates:
1. created ScaleChoicePropertyEditor to replace ScaleToFit
2. coded to resize image according to the choice of ScaleChoicePropertyEditor

to do:
1. code to resize on the android side
2. also apply the changes to ImageSprite
3. solve the issue that a picture returns to its original size after refreshing

**Comment by halatmit** [comment]
Thanks!



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by E-Hon** [comment]
hi @halatmit 
I got stuck at "Do not scale" mode on the android side and I raised a [question](https://groups.google.com/forum/#!topic/app-inventor-dev/DsVv9TWzkTE) in the group.
shall we wait a couple of days to see if i get any help? if i don't, then shall we just use "scale to fit" and "scale proportionally" for both Image and ImageSprite?

**Comment by halatmit** [comment]
@jisqyv @afmckinney 
Jeff and Andrew, please take a look.

**Comment by halatmit** [comment]
#692 was closed
