### ISSUE TITLE
Missing tooltips on blocks with dropdowns that have different variations visible in a drawer

### ISSUE THREAD

**Issue by jsheldonmit** [mit-cml/appinventor-sources#658]
When you hover over a small number of blocks, the tooltips do not display.

The pattern seems to be that in a group of related blocks that you can switch between with a drop-down menu, when the options are all shown in a particular drawer, only the top one displays the tool-tip correctly. FOr the others, the tool tip will never show.

For example, if you choose a "sin" block, the tooltip for that block will always display correctly, whether you hover over it in the drawer OR if you drag it onto the canvas and hover over it OR if you then change the dropdown to "cos" and hover over it (the correct tooltip always shows, cos is different than sin in this case).

HOWEVER, if you choose the "cos" block, the tooltip will never appear.

Confirmed In Chrome 47.0.2526.106 on Yosemite by 2 users including me

See linked video file for demonstration, confirmed by me. 
https://www.dropbox.com/s/q4w46h07240lhus/AppInventorBugwithSound.mp4?dl=0

**Comment by halatmit** [comment]
It looks like the bug is in math.js in the definition of math_cos at line 852 (and similarly for the other trig blocks -- and perhaps other non-trig blocks) where  it's getting the tooltip from the math_trig dropdown.
If that's the problem it could be an easy fix -- but looking at the way we're coding math_cos and math_trip that seems to be viollatiing DRY.   Maybe something to clean up?

**Comment by abhijit5893** [comment]
[Fixed it](https://github.com/mit-cml/appinventor-sources/pull/745). Here is a [screen capture](https://www.dropbox.com/s/gnjuzr6gt0bl93r/Bug%23658.mov?dl=0) showing the fix. It was indeed a very small bug in math.js

**Comment by halatmit** [comment]
#745 was merged
