### ISSUE TITLE
Internationalize "OK" and "CANCEL"

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#677]
.. and check the other button texts

**Comment by jisqyv** [comment]
@halatmit I agree that we should fix this, but I am concerned about doing so outside of a general plan to internationalize the runtime. Otherwise we will start getting complaints which state that the dialogs are internationalized, but other components are not.... and down the slippery slope we go...

Btw. I suspect the correct thing to do in this particular case is to use the system default (which it looks like we are doing for the cancel button but not the OK button!).

-Jeff

**Comment by halatmit** [comment]
I didn't know one could easily use the system default.    Is that
documented?  Where?



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by josmas** [comment]
@halatmit It depends on the particular piece of code; if you look at the Notifier [here](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/components/src/com/google/appinventor/components/runtime/Notifier.java#L218) you can see why the first two buttons can appear in the language the app is being developed, but ***Cancel*** is hardcoded in English only. In other cases some translations can be provided by the SDK when using the default widget.

We would need to extract all the hardcoded pieces and provide resources with translation files, in a similar way to what is done for the blocks and the designer, and then let the locale decide what to do.

I agree with @jisqyv that this needs a ***general plan***, as it will need some poking around the build server to provide language resources ([guide for internationalisation](http://developer.android.com/training/basics/supporting-devices/languages.html)).

**Comment by halatmit** [comment]
@josmas Why don't we  just localize the "cancel" string to the same language as the blocks?    I realize that the actual right thing to do is to translate according to the device setting rather than the developer's language, but we're not doing that for other text strings, and I'd think this half-measure is better than always having "cancel" in English.  Am I missing something?

**Comment by josmas** [comment]
@halatmit we will need to localise in a similar way to the blocks, but this is **runtime** in the app itself; I don't think we have access to the current localisation infrastructure written for the appengine project from the Components project. I guess it could be hacked in some way, but it would be really ugly. In the same way that we need two different strategies for Blockly and for GWT, we'll need a third one for the app itself; mostly because the platforms are very different.

**Comment by halatmit** [comment]
I think I understand what you are saying, and why one might prefer to do it
at runtime.    But - for now - why not treat the "cancel" string the same
way as treat, the names of methods or properties -- they are set
(statically) when the developer chooses the language to work in.  I
understand that this is not the same language that the phone's user might
want.   But it's better that making it always be english.   am I missing
something?



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by josmas** [comment]
I am not very familiar with the approach used for the designer; is it an annotation that is used? for instance, from OdeMessages:
```
@DefaultMessage("TinyDB")
@Description("")
String tinyDBComponentPallette();
```
In GWT code you can used the function defined, but how do you use that from a Component file? It's obviously being used somehow, but don't know how it is wired. It would be rather ugly to do it that way, but I guess it's somehow possible.

**Comment by halatmit** [comment]
I'll play with it and take a look.  Maybe I'm missing something.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by cpseager** [comment]
Maybe get a localised default here (works for ok too):

    string s = getActivity().getString(android.R.string.cancel);

In XML

     @android:string/cancel

**Comment by josmas** [comment]
thanks for your input, @cpseager 

Actually, for this particular case, it could work. We don't define layouts or string resources in XML, but _cancel_ and _ok_ are part of the SDK. Something like this could work (haven't tried it though!):
```
new Runnable() {public void run() {AfterChoosing(activity.getString(android.R.string.cancel));}}
```

Unfortunately, it wouldn't work for other cases such as https://github.com/mit-cml/appinventor-sources/issues/546

**Comment by jisqyv** [comment]
There are three issues/things to do here. One is to use the Android locale strings for strings displayed by Android components, such as OK and Cancel in dialog boxes. Things like:

    string s = getActivity().getString(android.R.string.cancel);

The second one is internationalizing strings provided us like the strings in the About this application box. For that we would need to provide a set of strings indexed by the locale they are for. They can then be set at runtime based on locale. We would also have to have a default in case we don't have a string for the particular locale of the device.

Finally we need to have a way to support the App Inventor programmer who wishes to provide different strings based on the locale of the device. This is probably the hardest thing to do because we still want to make building apps easy...

-Jeff

**Comment by halatmit** [comment]
I suggest we do only the first of Jeff's three things now, and file the other two as future issues.
The current Noifier asks the developer to provide the string corresponding to OK and I'd like keep it like that and use the locale method only for "Cancel" (for now).

**Comment by halatmit** [comment]
#685 handles CANCEL text

**Comment by halatmit** [comment]
#685 was closed
