### ISSUE TITLE
Interface objects copy and paste

### ISSUE THREAD

**Issue by Lasith-Niro** [mit-cml/appinventor-sources#726]
I made 6 to 7 apps using MIT appinventor. So I faced this problem.In design view developer can't copy and paste objects.

**Comment by josmas** [comment]
I am setting this to future work.

Thanks @Lasith-Niro. Unless you are willing to work on an issue, please discuss requirements in the [open source group](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev) instead of opening issues here directly. Thanks!

**Comment by E-Hon** [comment]
Hi @Lasith-Niro, I tried to move this issue to a [discussion](https://groups.google.com/forum/#!topic/app-inventor-open-source-dev/8kYfbw7r0m4) in the open source group. It would be great if you can provide some input to it. Hopefully, bit-by-bit we may make the idea more concrete so that it will be realized one day.

So would you close this issue and discuss it there?

**Comment by caldog6** [comment]
any chance of this being implemented? having to recreate elements of a page alongside doing hacky stuff just to duplicate screens feels very archaic and it's a waste of time
