### ISSUE TITLE
Looking for guidance on how to run load-tests on AppInventor standalone server

### ISSUE THREAD

**Issue by xuwenbin** [mit-cml/appinventor-sources#882]
Thanks to the great documentation on [how to build your own AppInventor server](https://docs.google.com/document/pub?id=1Xc9yt02x3BRoq5m1PJHBr81OOv69rEBy8LVG_84j9jc); I am able to set up my own AI2 server and make it serve test traffic.

Now, before my server could start serving real production traffic, I want to understand its performance limits (e.g. max. concurrent requests, latency, etc.).

It would be highly appreciated if one can provide me with the guidance, documentations, and/or directions on source code on how to conduct performance test in AI2.

-wenbin

**Comment by david2410** [comment]
From `Readme.md`, I just found this

>###Running tests The automated tests depend on Phantomjs. Make sure you install it and add it to your path. After that, you can run all tests by typing the following in a terminal window:

`$ ant tests`

**Comment by weihuali0509** [comment]
@xuwenbin If you are thinking running your own instance, I would advise you not to do that because the deployment method you are following above is just for development & testing. It won't handle the real production traffic. If you are in China, I would strongly recommend you to use the Guangzhou server - http://app.gzjkw.net/

**Comment by ewpatton** [comment]
@xuwenbin If you're still interested in an answer to this, please ask in the open source group at community.appinventor.mit.edu.
