### ISSUE TITLE
Online image loading causes stuck and "no response"

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#935]
i think we should use another thread to download the image, and put the image with runOnUiThread after the image is doanloaded in local.

**Comment by moliata** [comment]
Agree with this, I will look into this right now.

**Comment by ColinTree** [comment]
i had got a extension for this:

[cn.colintree.aix.AsyncImageLoader.zip](https://github.com/mit-cml/appinventor-sources/files/1326558/cn.colintree.aix.AsyncImageLoader.zip)

**Comment by moliata** [comment]
Actually no, I checked the code & it works the way it should work. AsyncTask does the job.

**Comment by ColinTree** [comment]
it is, as the method is used like this in ButtonBase.java
![image](https://user-images.githubusercontent.com/22613139/30773462-88092468-a0a3-11e7-87f5-1e396def5687.png)

**Comment by ColinTree** [comment]
though the method in MediaUtil is async, the Drawable reference here is linear.

so that is what happened

**Comment by moliata** [comment]
As you know MediaUtil is async. In Java linear methods are running on the same thread, which causes issues. So. when there is AsyncTask in MediaUtil, which causes Android to create a new thread. So, if methods are async, MediaUtil.getBitmapDrawable() doesn't hold the app, it continues app to work & goes back to the MediaUtil.getBitmapDrawable() method only when it has the result.

**Comment by ewpatton** [comment]
This was done intentionally. Images have always been loaded synchronously in App Inventor. Typically this wasn't a problem because most images come from the assets or SD card and so they load quickly. However, sometimes people load images from the web and this will ultimately depend on network connectivity.

A while back, there was an issue where adding Firebase resulted in a network on main thread exception, so we implemented an asynchronous version. However, this caused problems because on some devices the flash is slow so loading images was no longer "instantaneous" particularly for large images. The compromise was to do the loading asynchronously and block the thread with a lock so that we would stay as close to the original behavior as possible without the exception. Now in cases where the network is slow you may get an ANR message but that is the current compromise.

**Comment by ColinTree** [comment]
so in my extension, a new thread is created for getting the drawable from MediaUtil.
after got the drawable, it runs runOnUiThread and set it into the button.
![image](https://user-images.githubusercontent.com/22613139/30773520-eb7b50d8-a0a4-11e7-95c2-524003e3ce23.png)
![image](https://user-images.githubusercontent.com/22613139/30773523-f25cbd9c-a0a4-11e7-944d-23405c457eed.png)
![image](https://user-images.githubusercontent.com/22613139/30773524-f86473a6-a0a4-11e7-8745-533334543c9a.png)

**Comment by ColinTree** [comment]
so you mean if the image is too large, and the network is very slow, my solution here is going to causes problem if the Activity has been destroyed?

**Comment by ewpatton** [comment]
@ColinTree In this case I think your code will do the right thing, so long as you understand that it might take a potentially significant amount of time for the images to appear. The problem we had was that loading images went from being synchronous to asynchronous and this caught users by surprise. Note that you could simplify your code by using [getBitmapDrawableAsync](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/components/src/com/google/appinventor/components/runtime/util/MediaUtil.java#L388), which is the asynchronous portion of our image loading code.

**Comment by ColinTree** [comment]
may be add a switch in Screen1? 

thank you for your advice, i will simplify it and  release this in public. at least this can be a choice for users.
