### ISSUE TITLE
Notifier Bug - reported from forums

### ISSUE THREAD

**Issue by farxinu** [mit-cml/appinventor-sources#991]
Reported here: https://groups.google.com/forum/#!category-topic/mitappinventortest/aIMYI9sVBkk

If there are two notifiers within a procedure, they display in reverse order from the order in the blocks themselves.

**Comment by ewpatton** [comment]
Actually this is not a bug. When one opens two notifiers, the first is put onto the activity stack and then the second. You see them in the inverse order because the last one is the top-most (both are "visible"). When you dismiss the topmost one, you get the one previously on the stack. When you only open one, this would be your activity, but in this case it is the first notifier. If we solved #977 we could make this behave how people expect. Without that, this is the correct behavior.

**Comment by farxinu** [comment]
I realized that after Taifun said something. I wasn’t thinking and just saw “Hey it’s a bug let me report it”.
