### ISSUE TITLE
Disable events does not work for Companion unless reload screen

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#994]
While using companion, enable an disabled event is applied immediately, but disable a event is not, it can still be called until the whole screen is reloaded.

**Comment by ewpatton** [comment]
Related to #822

**Comment by ewpatton** [comment]
The underlying cause of this issue is that define-event is only generated when the block is enabled. There isn't a macro, let's say `undefine-event` that can be used to clean up the old version. One thing that may make sense for the Companion is whether to, when the form is cleared, also clear out the known event handlers used by EventDispatcher. This would require a change in runtime.scm.

**Comment by ewpatton** [comment]
Another wrinkle here is that all events in the Companion are in the same namespace. Therefore, let's say you have a disabled event in Screen1 and that same event in Screen2. Switching to Screen2 and back to Screen1 will overwrite the disabled event handler in Screen1 with Screen2's implementation, and firing of that event will invoke Screen2's behavior.
